# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: matador - take your database by the horns
email: sascha.kuehl@gmx.net
description: > # this means to ignore newlines until "baseurl:"
  matador is an object relational mapping framework written in C++.
  It aims to encapsulate all database backend communication. You don't
  have to deal with database backends or sql statements neither with
  mapping of data types or serialization of objects. It comes with
  relation handling out of the box, brings a unique container for all
  kind of objects, a fluent sql query interface. On top all features
  are combined into a ORM layer.
url: "https://zussel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/matador" # the subpath of your site, e.g. /blog
twitter_username: zussel72
github_username:  zussel

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

include:
- _pages

# # Defaults
# defaults:
#   # _pages
#   - scope:
#       path: ""
#       type: pages
